In [7]:
import matplotlib.image as img
import numpy as np

#đọc ảnh
pic = img.imread("small_color.png");

# lấy chiều rộng, chiều cao của ảnh
w, h = pic.shape[:2];
print(pic.shape[0:2])
print(w)
print(h)

# chiều rộng, chiều cao mới
xNew = int(w * 4);
yNew = int(h * 4);

#tỉ lệ hình mới và hình cũ
xScale = xNew/(w);
yScale = yNew/(h);

#tạo ma trận của ảnh mới
newImage = np.zeros([xNew, yNew, 3]);
print(newImage)

for i in range(xNew):
    for j in range(yNew):
        newImage[i, j]= pic[int(i / xScale),
                                    int(j / yScale)]

# Save the image after scaling
img.imsave('imgNearneighbor.png', newImage);

(100, 100)
100
100
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
